name: flutter_iap
description: in app purchases for flutter
version: 0.0.1
author: Jack ODonnell
homepage: https://github.com/JackAppDev/flutter_iap/

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.jackappdev.flutteriap
    pluginClass: FlutterIapPlugin